// Merges content/lessons.json (curated) + content/handbook-auto.json (phase 2)
// into content/lessonsData.ts for Metro-safe app imports.
// Run with: node scripts/json-to-ts.js
// (Regenerate whenever either JSON file changes.)
const { readFileSync, writeFileSync, existsSync } = require("node:fs");
const { join } = require("node:path");

const root = join(__dirname, "..");
const curatedPath = join(root, "content", "lessons.json");
const autoPath = join(root, "content", "handbook-auto.json");
const dest = join(root, "content", "lessonsData.ts");

const curated = JSON.parse(readFileSync(curatedPath, "utf8"));
let auto = [];
if (existsSync(autoPath)) {
  auto = JSON.parse(readFileSync(autoPath, "utf8"));
}

// Guard against id collisions between curated and auto bundles.
const seen = new Set();
for (const l of [...curated, ...auto]) {
  if (seen.has(l.id)) throw new Error(`Duplicate lesson id: ${l.id}`);
  seen.add(l.id);
}

const merged = [...curated, ...auto];

const out =
  "import type { Lesson } from '../lib/types';\n\n" +
  "// Generated by scripts/json-to-ts.js — do not edit directly.\n" +
  "// Sources: content/lessons.json (curated) + content/handbook-auto.json (phase 2).\n" +
  "export const lessonsData: Lesson[] = " +
  JSON.stringify(merged) +
  ";\n";

writeFileSync(dest, out);
console.log(
  `Merged ${curated.length} curated + ${auto.length} auto → ${dest} (${merged.length} lessons)`,
);
